In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('total_power.csv')
df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_3852\1163825618.py:1: DtypeWarning: Columns (2,6,7,8,11,36,37,38,39,40,41,42,43,44,46,52,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('total_power.csv')

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48437,377732,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.1,60,60,1,Y,SYSTEM,2026-04-08 10:35:03,\N
48438,377733,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,35.5,60,60,1,Y,SYSTEM,2026-04-08 10:40:00,\N
48439,377734,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.7,60,60,1,Y,SYSTEM,2026-04-08 10:40:03,\N
48440,377735,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,36.0,60,60,1,Y,SYSTEM,2026-04-08 10:45:00,\N
48441,377736,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1,Y,SYSTEM,2026-04-08 10:45:03,\N

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48442 entries, 0 to 48441
Data columns (total 63 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQ                                  48442 non-null  int64
 1   PowerPlantID                         48442 non-null  object
 2   Device                               48442 non-null  object
 3   LCDBoot_ARCVersion                   48442 non-null  object
 4   ARCStatus_PVinputConfig              48442 non-null  object
 5   RegNum                               48442 non-null  int64
 6   ProVer                               48442 non-null  object
 7   MinorVer                             48442 non-null  object
 8   SN                                   48442 non-null  object
 9   model                                48442 non-null  object
 10  RWRegSum                             48442 non-null  int64
 11  RWRegAdd                             48442 non-null  object
 12  TYield                               48442 non-null  int64
 13  DYield                               48442 non-null  float64
 14  Eff                                  48442 non-null  int64
 15  PF                                   48442 non-null  float64
 16  Pmax                                 48442 non-null  float64
 17  RunT                                 48442 non-null  float64
 18  Pac                                  48442 non-null  float64
 19  Sac                                  48442 non-null  float64
 20  Uab                                  48442 non-null  float64
 21  Ubc                                  48442 non-null  float64
 22  Uca                                  48442 non-null  float64
 23  la                                   48442 non-null  float64
 24  lb                                   48442 non-null  float64
 25  lc                                   48442 non-null  float64
 26  Upv1                                 48442 non-null  float64
 27  Ipv1                                 48442 non-null  float64
 28  Upv2                                 48442 non-null  float64
 29  Ipv2                                 48442 non-null  float64
 30  Upv3                                 48442 non-null  float64
 31  Ipv3                                 48442 non-null  float64
 32  Freq                                 48442 non-null  float64
 33  Tmod                                 48442 non-null  float64
 34  Tamb                                 48442 non-null  float64
 35  Tcoil                                48442 non-null  float64
 36  Mode                                 48442 non-null  object
 37  Time                                 48442 non-null  object
 38  Pfault                               48442 non-null  object
 39  Warm                                 48442 non-null  object
 40  Fault0                               48442 non-null  object
 41  fault1                               48442 non-null  object
 42  fault2                               48442 non-null  object
 43  fault3                               48442 non-null  object
 44  fault4                               48442 non-null  object
 45  Qac                                  48442 non-null  float64
 46  PIDboxEnable                         48442 non-null  object
 47  PIDboxVoltage                        48442 non-null  float64
 48  PIDboxCurrent                        48442 non-null  float64
 49  Reservedforpidbox                    48442 non-null  object
 50  Reservedforpidbox2                   48442 non-null  object
 51  MajorVer                             48442 non-null  object
 52  PVdetection                          48442 non-null  object
 53  BusCapacitance                       48442 non-null  int64
 54  AcCapacitance                        48442 non-null  int64
 55  Pdc                                  48442 non-null  float64
 56  MaxActivePower                       48442 non-null  int64
 57  MaxApparentPower                     48442 non-null  int64
 58  DSPSecuritySpecificationVersionNumr  48442 non-null  object
 59  use_yn                               48442 non-null  object
 60  crt_usr                              48442 non-null  object
 61  crt_dttm                             48442 non-null  object
 62  udt_dttm                             48442 non-null  object
dtypes: float64(26), int64(9), object(28)
memory usage: 23.3+ MB

In [5]:
plant_df = df[df['PowerPlantID'] == 'GJM_GSG_SGD_0001']
plant_df

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48437,377732,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.1,60,60,1,Y,SYSTEM,2026-04-08 10:35:03,\N
48438,377733,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,35.5,60,60,1,Y,SYSTEM,2026-04-08 10:40:00,\N
48439,377734,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.7,60,60,1,Y,SYSTEM,2026-04-08 10:40:03,\N
48440,377735,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,36.0,60,60,1,Y,SYSTEM,2026-04-08 10:45:00,\N
48441,377736,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1,Y,SYSTEM,2026-04-08 10:45:03,\N

In [24]:
plant_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48408 entries, 0 to 48441
Data columns (total 63 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQ                                  48408 non-null  int64
 1   PowerPlantID                         48408 non-null  object
 2   Device                               48408 non-null  object
 3   LCDBoot_ARCVersion                   48408 non-null  object
 4   ARCStatus_PVinputConfig              48408 non-null  object
 5   RegNum                               48408 non-null  int64
 6   ProVer                               48408 non-null  object
 7   MinorVer                             48408 non-null  object
 8   SN                                   48408 non-null  object
 9   model                                48408 non-null  object
 10  RWRegSum                             48408 non-null  int64
 11  RWRegAdd                             48408 non-null  object
 12  TYield                               48408 non-null  int64
 13  DYield                               48408 non-null  float64
 14  Eff                                  48408 non-null  int64
 15  PF                                   48408 non-null  float64
 16  Pmax                                 48408 non-null  float64
 17  RunT                                 48408 non-null  float64
 18  Pac                                  48408 non-null  float64
 19  Sac                                  48408 non-null  float64
 20  Uab                                  48408 non-null  float64
 21  Ubc                                  48408 non-null  float64
 22  Uca                                  48408 non-null  float64
 23  la                                   48408 non-null  float64
 24  lb                                   48408 non-null  float64
 25  lc                                   48408 non-null  float64
 26  Upv1                                 48408 non-null  float64
 27  Ipv1                                 48408 non-null  float64
 28  Upv2                                 48408 non-null  float64
 29  Ipv2                                 48408 non-null  float64
 30  Upv3                                 48408 non-null  float64
 31  Ipv3                                 48408 non-null  float64
 32  Freq                                 48408 non-null  float64
 33  Tmod                                 48408 non-null  float64
 34  Tamb                                 48408 non-null  float64
 35  Tcoil                                48408 non-null  float64
 36  Mode                                 48408 non-null  object
 37  Time                                 48408 non-null  object
 38  Pfault                               48408 non-null  object
 39  Warm                                 48408 non-null  object
 40  Fault0                               48408 non-null  object
 41  fault1                               48408 non-null  object
 42  fault2                               48408 non-null  object
 43  fault3                               48408 non-null  object
 44  fault4                               48408 non-null  object
 45  Qac                                  48408 non-null  float64
 46  PIDboxEnable                         48408 non-null  object
 47  PIDboxVoltage                        48408 non-null  float64
 48  PIDboxCurrent                        48408 non-null  float64
 49  Reservedforpidbox                    48408 non-null  object
 50  Reservedforpidbox2                   48408 non-null  object
 51  MajorVer                             48408 non-null  object
 52  PVdetection                          48408 non-null  object
 53  BusCapacitance                       48408 non-null  int64
 54  AcCapacitance                        48408 non-null  int64
 55  Pdc                                  48408 non-null  float64
 56  MaxActivePower                       48408 non-null  int64
 57  MaxApparentPower                     48408 non-null  int64
 58  DSPSecuritySpecificationVersionNumr  48408 non-null  object
 59  use_yn                               48408 non-null  object
 60  crt_usr                              48408 non-null  object
 61  crt_dttm                             48408 non-null  object
 62  udt_dttm                             48408 non-null  object
dtypes: float64(26), int64(9), object(28)
memory usage: 23.6+ MB

In [6]:
cols = plant_df.columns
for col in cols:
    print(plant_df[col].unique())

[329295 329296 329297 ... 377734 377735 377736]
['GJM_GSG_SGD_0001']
['4034' 4034]
['ffff']
['ffff']
[79]
['1.00' 1.0]
['0.00' 0.0]
['1018282223012' '1018282225009' 1018282223012 1018282225009]
['HPC-060HL-V1-0U']
[92]
['1000' 1000]
[158096 140987 158097 ... 190976 170284 190979]
[175.1 156.7 176.6 ... 349.4 312.4 349.5]
[10  9  8  7  6  5  3  0  4  1]
[ 1.   0.9  0.8 64.8  0.6 65.2  0.3  0.   0.4  0.5 65.   0.7 64.9 64.7
 65.1 65.3 64.6  0.2]
[57.2 51.6  0.   0.3  0.5  0.6  0.7  0.9  0.8  1.2  1.1  1.3  1.8  1.6
  2.1  1.9  2.5  2.2  2.8  3.6  3.2  4.6  4.1  5.4  4.8  6.6  5.8  7.3
  6.4 10.5  9.3 15.9 14.1 18.8 16.5 19.2 17.1 28.  24.8 32.2 28.7 37.9
 34.1 40.3 36.1 45.  39.6 49.2 44.  44.8 50.5 45.3  0.4  1.5  1.4  2.
  2.4  3.1  3.3  2.9  4.3  3.8  4.7  8.   7.1  9.6  8.5 10.3  9.2 11.7
 10.4 19.3 16.6 19.7 17.6 19.8  3.4  3.   5.   4.4  5.2  8.3 12.2 10.8
 14.9 13.5 16.7 20.3 18.1 31.  33.8 30.2 35.2 31.5 37.5 33.5 41.  36.4
 42.2 37.8 43.3 38.2 44.2 40.  46.6 41.5 41.9 49.  43.4 51.  45.6 51.7
 46.4  2.3  2.6  2.7  3.7  6.7  5.9  9.4  8.4 10.9 12.  10.6 20.2 17.8
 23.9 21.3 26.4 23.3 27.  24.2 33.7 30.6 43.5 38.6 46.2 52.8 47.2  1.
  4.   3.9  5.5  4.9  6.1  6.9  6.2  7.2  7.9  7.   9.1  8.1  9.7  8.7
 10.2 13.7 12.1 14.  12.3 16.2 14.5 24.1 21.8 23.2 25.7 26.1 26.2 23.6
 26.9 24.  27.6 24.7 28.2 25.2 29.1 29.4 26.3 30.4 27.3 31.1 27.9 28.3
 32.1 28.9 32.4 29.2 33.1 29.8 33.3 30.  33.9 30.5 34.2 30.7 34.6 34.9
 31.4 35.4 31.8 35.5 32.  32.6 36.2 36.7 37.1 33.4 37.2 33.6 37.4 37.7
 34.5 38.9 35.  39.  35.1  1.7  3.5  8.2 11.2 10.  11.3 13.  11.6 19.9
 17.7 36.   4.5  6.   5.3  5.6 10.7 12.8 11.4 17.3 15.5 19.  17.2 44.9
 41.7 49.5 44.3 51.9 52.9 46.8 53.  47.4 53.3 47.8  4.2  5.7  9.5 11.1
 12.5 21.  34.  30.3 38.4 39.1 52.3 46.5 54.2 48.4  6.8  7.5  8.6  7.8
 10.1  9.  11.5 12.6 15.1 15.  16.9 40.4 41.6 37.3 36.5 32.8 40.5 58.9
 52.2 13.3 14.3 15.6 13.9 18.6 18.2 47.  48.9 51.8 55.7 50.1  6.3  7.7
 13.2 15.3 13.6 18.  16.  16.1 19.6 17.4 21.7 19.4 22.8 20.4 20.7 25.
 22.4 25.8 23.1 26.6 23.8 26.  26.8 43.7 44.5 39.7 40.1 40.8  7.4  6.5
  9.9 12.4 11.8 15.8 14.7 17.5 19.1 17.  20.8 18.5 21.6 22.3 22.9 21.1
 24.4 25.6 23.5 28.1 28.6 29.6 26.5 30.1 27.4 31.2 31.6 32.5 29.  32.7
 29.3 33.2 29.7 34.4 30.9 35.7 35.9 32.3 36.3  5.1  9.8 11.  14.2 13.4
 15.7 18.4 16.4 20.  21.4 23.  20.6 23.7 21.2 24.5 22.  25.1 22.6 27.1
 24.3 25.3 27.5 31.3 31.7 28.5 29.5 33.  34.7 35.3 31.9 36.6 32.9 14.8
 35.6 41.8 15.4 20.9 18.7 25.5 40.9  7.6 17.9 42.4  8.8 22.1 22.5 49.4
 51.2 45.1 28.8 35.8 42.5 36.9 48.5 43.2 18.9 16.8 22.7 26.7 24.6 25.9
 30.8 34.3 36.8 38.1 38.8 39.3 39.5 40.2 20.1 13.1 25.4 27.8 11.9 12.9
 16.3 15.2 27.2 34.8 37.6 38.3 38.5  8.9 21.5 22.2 23.4 28.4 14.4 27.7
 29.9 45.2 13.8 20.5 38.7 41.2 41.4 14.6 21.9 37.  19.5 18.3 24.9  0.2
 43.1 45.8 41.1 12.7 42.1 43.6 45.9 46.3 48.3 39.2 44.4 42.  44.7 39.8
 47.9 42.3 43.9 38.  39.4 42.9 44.1 42.7 39.9 40.7 46.1 40.6 48.7 41.3
 43.  45.4 50.8 45.5 50.9 45.7 48.8 54.8 46.  47.7 42.6 51.1 47.1 47.5
 47.6 43.8 49.8 42.8 44.6 52.7 53.6 49.7 53.5 56.1 46.7 49.1 54.7 47.3
 53.9 60.1 46.9]
[547.9 547.1 552.9 ... 767.9 771.7 768.8]
[14.  12.1 33.9 31.9  9.9  8.8 10.7  9.7  9.1  8.3 13.3  8.9  9.3  8.
  7.1  8.4  7.5  7.6  6.8  7.4  6.7  6.2  5.5  6.5  5.8  5.6  5.   4.5
  4.   3.4  3.   1.8  1.6  1.1  1.   1.3  1.2  2.1  1.9  1.4  0.9  0.6
  0.2  0.   0.3  0.5  0.7  0.8  2.5  2.2  2.8  3.6  3.2  4.6  5.4  4.8
  7.   6.3  5.1  4.9  5.2  4.7  4.2  4.3  3.8  5.7 10.  14.2 12.6  7.9
  6.9  8.1 11.8 10.5 17.4 15.5 18.8 16.4 12.3 11.   9.8 13.8 12.2 13.7
 10.3 28.  24.6 14.4 14.7 13.1 13.5 10.8 14.8 13.2 20.9 18.4 19.8 17.9
 37.3 33.3 36.5 32.6 16.1 18.3 15.9 13.4 12.  16.3 14.5 16.8 15.  17.5
 15.7 11.7 12.7 20.  18.2 14.3 25.2 42.3 37.2 19.3 41.2 30.1 23.7 20.4
 22.6 20.5 49.1 44.4 19.1 16.9 15.3 13.6 16.7 20.2 18.1 18.9 22.4 19.9
 18.5 30.9 28.3 22.5 16.2 19.  18.6 24.  21.4 27.5 24.5 20.8 10.4  6.1
  7.7  7.8 10.2  9.2  8.2  3.7  3.3  5.3  2.9  2.6  4.4  2.7  2.4  1.5
  0.4  2.   1.7  3.1  2.3  4.1  6.   6.4  8.7  3.9  3.5  9.6  8.5  9.5
 10.9 11.2  7.2 13.   9.4 10.6 11.6 25.  20.1 22.2 27.  22.7 25.9 22.3
  9.  33.6 35.3 31.6 35.4 31.8 17.6 12.9 38.  34.1 39.5 37.1 33.2 21.
 22.9 39.1 15.8 13.9 38.1 35.5 11.3 39.6 16.6 42.6 36.8 34.6 42.5 27.4
 28.2 27.2 26.2 48.7 40.3 15.6 14.1 17.2 46.4 19.7 41.9 40.4 27.8 35.6
 27.3 24.8 21.5 19.2 17.  25.6 24.4 21.6 31.3 41.4 39.  26.4 23.5 27.6
 23.9 16.5 12.5 11.9 19.4 17.7 23.3 37.6 34.  26.6 21.1 23.6 20.7 33.7
 12.4 14.9 17.8 10.1 12.8  8.6  7.3  6.6  5.9 11.1 17.3 20.3 18.  25.7
 23.  24.7 18.7 25.1 14.6 34.7 24.9 21.8 48.2 42.8 23.1 38.3 43.3 39.7
 24.2 16.  11.4 26.  32.1 43.6 39.2 48.  43.2 44.2 36.3 22.1 15.4 28.9
 29.2 21.3 19.6 46.6 30.7 32.7 41.6 38.6 42.4 38.4 34.2 33.1 36.9 35.9
 32.3 35.8 36.6 32.9 35.2 17.1 35.7 31.2 26.1 29.8 29.3 26.5 23.8 25.8
 23.4 23.2 22.  21.7 15.2 21.2 25.5 26.9 24.1 28.1 29.1 28.4 30.3 30.6
 30.8 28.7 32.4 29.9 30.5 34.5 31.  34.8 36.7 33.5 37.4 37.5 37.7 38.2
 35.  38.7 34.9 37.8 38.8 32.8 37.  31.4 31.5 32.  34.3 29.6 33.4 30.2
 32.2 32.5 29.5 27.1 26.7 26.3 19.5 30.  11.5 28.6 36.1 42.2 15.1 46.9
 41.8 41.3 29.  44.8 45.9 40.7 46.5 41.7 40.  36.  33.8 30.4 36.4 25.3
 27.7 22.8 20.6 24.3 31.1 27.9 21.9 44.1 49.6 36.2 34.4 40.9 35.1 40.1
 41.5 39.8 43.1 25.4 48.9 37.9 40.6 44.9 40.5 33.  29.4 28.8 31.7 39.9
 38.9 28.5 29.7 26.8 39.3 39.4 43.5 42.  38.5 40.2 42.7 43.8 40.8 41.
 45.7 47.1 44.6 42.1 41.1 43.  42.9 43.4 43.7 46.1 45.3 44.  49.4 44.3
 49.3 46.8 49.5 50.6 45.  50.2 45.2 51.1 45.1 45.6 45.5 44.7 44.5 43.9
 47.2 47.9 46.7 45.4 45.8 53.9 46.2 47.3 49.8 47.4 46.3 47.  47.5]
[14.  12.1 33.9 31.4  9.9  8.8 10.7  9.7  9.1  8.3 13.3  8.9  9.3  8.
  7.1  8.4  7.5  7.6  6.8  7.4  6.7  6.2  5.5  6.5  5.8  5.6  5.   4.5
  4.   3.4  3.   1.9  1.6  1.1  1.3  2.1  1.8  1.4  1.   0.6  0.2  0.
  0.3  0.5  0.7  0.9  0.8  1.2  1.7  2.2  2.   2.6  2.8  2.5  3.6  3.2
  4.6  5.4  4.8  7.   6.3  5.1  4.9  5.2  4.7  4.2  4.3  3.8  5.7 10.
 14.2 12.6  7.9  6.9  8.1 11.8 10.5 17.4 15.5 18.8 16.4 12.3 11.   9.8
 13.8 12.2 13.7 10.2 28.  24.6 14.4 14.7 13.1 13.5 10.8 14.8 13.2 20.9
 18.4 19.8 17.9 37.3 33.3 36.5 32.6 16.1 18.3 15.9 13.4 12.  16.3 14.5
 16.8 15.  17.5 15.7 11.7 12.7 20.  18.2 14.3 31.9 25.2 42.3 37.2 19.3
 40.2 30.1 23.7 20.4 22.6 20.5 49.1 44.4 19.1 16.9 15.3 13.6 16.7 20.2
 18.1 18.9 22.4 19.9 18.5 30.9 28.3 22.5 16.2 19.  18.6 24.  21.4 27.5
 24.5 20.8 10.4  6.1  7.7  7.8  9.2  8.2  3.7  3.3  5.3  3.1  2.7  4.4
  2.9  1.5  0.4  2.3  2.4  4.1  6.   6.4  8.7  3.9  3.5  9.6  8.5  9.5
 10.9 11.2  7.2 13.   9.4 10.6 11.6 25.  20.1 22.2 27.  22.7 25.9 25.5
  9.  33.6 35.3 31.6 35.4 31.8 17.6 13.9 12.9 38.  34.1 39.5 37.1 33.2
 21.  22.9 39.1 15.8 38.1 35.5 11.3 39.6 16.6 42.6 41.4 34.6 42.5 27.4
 28.2 27.2 26.2 48.8 40.3 15.6 14.1 17.2 46.5 19.7 41.9 40.4 27.8 35.6
 27.3 24.8 21.5 19.2 17.  25.6 24.4 21.6 31.3 39.  26.4 23.5 27.6 23.9
 16.5 12.5 11.9 19.4 17.7 23.3 37.6 34.  26.6 21.1 23.6 20.7 33.7 12.4
 14.9 17.8 10.1 12.8 10.3  8.6  7.3  6.6  5.9 11.1 17.3 20.3 25.7 23.
 24.7 18.7 25.1 14.6 34.7 24.9 21.8 48.3 42.8 23.1 38.3 43.3 39.7 24.2
 16.  11.4 26.  32.1 43.6 39.2 48.  43.2 44.2 36.3 22.1 15.4 28.9 29.2
 21.3 19.6 46.6 30.7 32.7 41.6 38.6 42.4 38.4 34.2 36.8 33.1 36.9 35.9
 32.3 35.8 36.6 32.9 35.2 17.1 35.7 31.2 26.1 29.8 29.3 26.5 23.8 25.8
 23.4 23.2 22.  21.7 15.2 21.2 22.3 26.9 24.1 28.1 29.1 28.4 30.3 30.6
 30.8 28.7 32.4 29.9 30.5 34.5 31.  34.8 36.7 33.5 37.4 37.5 37.7 35.
 38.7 34.9 37.8 38.8 32.8 37.  31.5 32.  34.3 29.6 33.4 30.2 32.2 32.5
 29.5 27.1 26.7 26.3 19.5 30.  11.5 24.3 27.9 28.6 36.1 42.2 15.1 47.
 41.8 29.  44.9 45.9 40.7 41.7 40.  36.  33.8 30.4 36.4 25.3 27.7 22.8
 20.6 31.1 21.9 44.1 49.6 36.2 34.4 40.9 18.  35.1 40.1 41.5 39.8 43.1
 25.4 49.  41.2 40.5 37.9 40.6 39.9 33.  29.4 28.8 31.7 38.9 42.  29.7
 26.8 28.5 38.2 39.3 39.4 43.5 38.5 42.7 43.8 40.8 41.1 45.7 47.1 48.2
 41.  44.6 42.1 41.3 44.5 43.  44.3 42.9 43.4 43.7 44.7 46.1 45.3 44.
 49.4 49.3 46.8 50.7 50.3 45.2 51.2 45.1 44.8 45.6 45.5 43.9 47.2 46.4
 47.9 46.7 45.  45.4 45.8 53.9 46.2 47.3 49.8 47.4 48.9 46.3 47.5 46.9]
[395.7 396.  399.3 400.1 395.9 396.6 397.  396.9 396.7 396.5 395.6 396.1
 396.3 398.8 399.  398.  398.6 398.1 398.9 398.7 399.7 400.4 399.4 400.2
 395.5 396.2 396.4 398.4 394.  393.9 393.1 393.3 393.4 394.9 394.8 394.7
 394.6 395.2 395.3 392.6 392.8 393.2 393.  391.9 391.1 391.6 392.1 389.6
 389.2 390.2 390.6 390.7 389.9 389.8 390.8 389.4 393.5 393.7 394.4 394.5
 393.6 393.8 394.2 395.4 394.3 394.1 392.  392.3 392.4 392.7 392.5 391.7
 391.  398.5 397.7 397.8 397.6 398.2 397.9 399.8 397.1 397.4 397.5 397.2
 400.9 401.3 399.6 400.  402.  402.5 401.8 401.5 399.9 400.3 401.  400.8
 399.1 403.4 403.8 406.4 405.6 401.9 402.1 406.5 406.9 401.6 401.7 404.1
 403.3 401.2 402.2 407.1 401.1 400.7 400.6 399.5 399.2 396.8 397.3 395.8
 398.3 400.5 395.  395.1 392.9 391.3 391.5 389.1 389.5 388.8 388.5 391.8
 391.2 390.5 390.3 391.4 390.9 402.4 402.9 403.1 401.4 404.8 405.3 403.7
 404.  403.  404.2 404.5 404.6 402.6 407.2 407.6 402.7 402.8 407.7 408.3
 402.3 403.2 388.9 406.  404.7 404.4 403.5 404.3 405.2 405.  390.4 389.7
 403.6 404.9 405.4 406.2 405.8 406.1 405.1 390.  388.6 390.1 389.3 392.2
 389.  406.8 407.  406.3 406.7 408.  405.5 407.4 407.8 408.1 403.9 408.7
 408.9 408.2 409.5 409.2 409.  408.5 409.7 409.8 410.4 410.3 406.6 405.9
 407.3 408.6 405.7 407.5 388.7 387.9 387.4 387.7 388.1 387.5 388.4 388.2
 409.6 388.3 385.9 386.6 386.5 407.9 410.1 410.  410.2 387.8 387.3 387.6
 388.  384.8 386.2 386.8 386.7 387.  387.2 386.9 386.3 387.1 386.4 385.7
 409.3 383.6 385.1 382.9 409.9 410.7 410.8 385.5 384.7 385.3 408.4 385.8
 410.6 411.4 411.7 411.  409.4 409.1 386.1 411.6 411.9 410.9 408.8 411.5]
[395.6 395.2 399.3 395.8 395.3 396.8 396.4 396.9 396.  395.7 395.4 395.5
 396.3 396.1 398.9 398.3 398.  397.7 398.2 398.1 398.7 399.  399.7 399.5
 395.9 396.6 397.  397.3 397.5 398.6 394.  393.1 392.6 392.3 393.2 393.6
 393.5 395.1 394.1 394.7 394.5 394.3 393.3 392.8 391.8 391.9 391.7 390.1
 388.9 390.8 390.  391.  390.5 391.1 389.7 390.4 389.4 390.3 390.6 389.8
 389.1 393.9 393.4 394.8 393.  394.2 394.4 393.7 392.2 392.4 392.7 392.
 391.6 391.2 397.2 397.8 397.1 397.6 396.7 397.9 399.9 396.5 401.  400.4
 399.4 398.8 401.7 401.5 401.6 399.6 400.  400.3 400.9 399.8 399.2 400.5
 400.1 402.9 402.6 406.1 404.4 401.9 401.3 406.3 405.8 400.7 403.8 402.3
 401.8 401.1 401.4 400.2 406.2 406.  400.8 400.6 398.4 398.5 397.4 399.1
 396.2 394.9 395.  394.6 393.8 392.5 391.4 390.2 389.9 389.6 389.3 389.5
 388.5 392.9 390.7 391.5 392.1 402.1 402.4 404.2 403.7 403.  402.5 402.7
 403.1 404.3 403.6 404.1 406.6 407.  388.4 390.9 405.  404.  402.8 402.2
 404.8 391.3 388.8 389.  401.2 402.  403.4 403.3 405.7 404.9 405.1 404.6
 405.4 403.9 403.5 404.7 405.2 388.3 389.2 406.5 405.6 407.1 405.3 406.4
 403.2 404.5 407.3 406.7 407.6 407.9 407.2 408.7 408.2 407.7 408.  409.5
 408.5 405.9 407.5 405.5 388.  388.7 388.6 406.8 407.8 387.9 387.8 387.5
 388.1 388.2 387.7 386.4 385.8 406.9 409.  387.6 386.8 387.3 387.2 386.7
 386.9 387.  386.5 387.1 386.6 387.4 386.2 386.3 386.  386.1 385.1 385.4
 384.1 408.3 408.6 409.3 409.8 407.4 408.9 410.2 408.1 408.8 408.4 385.7
 410.4 410.  409.6 409.2 409.4]
[394.8 394.  398.2 397.9 395.3 396.  395.5 395.7 395.1 394.5 394.4 396.1
 395.6 398.5 397.5 396.5 397.1 398.3 398.9 397.7 399.6 399.4 399.1 395.4
 394.9 396.7 397.  396.3 397.6 397.3 398.8 397.8 393.9 393.7 392.4 393.2
 394.3 394.1 395.9 394.7 396.2 395.  394.6 393.8 391.9 390.4 392.9 390.5
 389.8 388.7 390.8 389.9 390.6 389.2 390.7 389.1 392.5 393.5 391.7 393.1
 393.6 392.6 393.3 392.7 392.3 391.6 391.4 390.9 391.2 392.1 391.8 390.1
 391.5 389.3 396.4 399.2 398.4 396.8 402.  400.3 400.5 399.7 398.  398.1
 399.5 400.9 400.1 404.3 402.5 404.5 403.9 400.  398.7 402.1 400.4 400.2
 399.8 399.9 404.7 404.4 399.  397.4 398.6 396.9 395.2 396.6 397.2 395.8
 393.4 394.2 399.3 391.3 391.1 390.  389.4 389.5 388.3 392.8 391.  392.2
 389.7 388.2 392.  390.2 393.  390.3 402.7 400.8 401.5 401.1 401.2 401.6
 404.6 404.  402.4 400.7 388.9 400.6 404.1 403.2 401.9 401.  403.4 401.4
 388.8 387.9 403.1 404.2 402.2 403.  403.5 402.8 403.6 401.3 389.  389.6
 388.5 401.8 405.4 403.7 402.9 401.7 402.6 405.2 402.3 405.9 388.6 388.4
 387.5 405.7 405.1 406.  388.  388.1 387.8 405.  387.7 387.2 403.3 387.3
 387.6 386.6 385.7 403.8 387.4 386.9 386.1 386.8 386.2 387.1 387.  386.5
 386.7 404.8 405.6 405.3 406.7 404.9 386.  407.  406.2 405.8 405.5]
[20.9 18.1 49.  45.9 14.8 13.1 15.6 14.2 13.6 12.2 19.6 17.7 14.7 13.2
 13.8 12.3 11.7 10.5 12.4 11.1 11.2 10.1 10.9 11.   9.9  9.1  8.1  9.5
  8.5  8.3  7.4  6.7  5.9  5.   4.4  2.9  2.6  2.2  2.   2.3  3.2  2.8
  2.4  1.9  1.8  1.6  1.4  1.2  0.   1.3  1.1  1.5  1.7  2.5  3.3  3.
  3.8  3.4  4.2  5.3  4.8  6.9  6.1  8.   7.1  9.8  8.6  9.3  7.7  8.2
  8.7  7.9  6.4  6.5  5.7  7.5  6.8  7.8 10.6 15.  13.3 21.1 18.8 11.9
 10.4 10.7  8.8 17.4 15.5 25.7 22.7 27.6 24.2 16.2 14.6 13.  20.3 20.1
 18.  15.1 13.5 40.6 35.9 24.1 21.2 21.7 19.4 20.2 19.9 17.8 16.  14.4
 15.9 21.6 21.8 30.9 27.  28.8 26.  53.8 48.2 52.8 47.  26.3 23.6 30.7
 26.8 23.3 20.7 19.7 17.5 23.7 24.5 25.4 22.8 19.3 17.2 18.7 29.4 21.
 18.6 46.6 39.6 60.9 54.1 28.  58.4 51.8 23.9 20.8 42.4 35.1 25.2 22.4
 30.2 25.8 33.  29.8 70.1 63.2 27.8 24.7 22.5 24.4 29.3 26.2 32.6 29.
 24.  45.  41.  32.9 26.7 24.9 27.3 35.  31.1 39.9 35.5 26.5 27.7 30.5
 27.1 25.5 22.6 30.4 17.3 14.5 12.9 15.2 11.6 10.   9.  11.5 10.2 10.3
  7.6  9.4  8.4 13.4 13.7 12.1  5.6 11.4  7.   5.5  4.5  4.   7.3  6.6
  7.2  6.3  4.3  3.9  3.6  2.7  2.1  4.6  3.7  4.7  6.2  3.1  4.1  5.4
 11.8  8.9  9.6  9.7  9.2  4.9  5.1  5.2  6.  14.1 12.6 14.  12.5 16.5
 17.6 21.5 19.   3.5  5.8 13.9 15.7 17.9 19.5 37.2 32.1 30.1 39.3 34.8
 35.2 15.4 48.7 43.7 51.2 50.9 46.5 20.4 55.  49.4 57.1 51.1 48.1 31.8
 31.7 55.7 22.9 56.6 50.5 56.7 50.7 51.3 27.2 25.3 63.1 46.3 55.3 61.2
 54.9 39.5 39.1 36.3 16.6 27.5 69.3 59.7 20.5 23.4 31.3 26.6 64.7 59.6
 60.2 37.7 45.7 39.7 39.4 35.7 28.1 36.8 33.3 36.1 31.5 41.1 59.9 56.2
 56.9 38.8 34.2 40.2 29.6 24.3 18.4 20.6 26.9 31.4 28.5 29.1 25.9 30.6
 34.7 54.4 49.2 38.2 34.9 33.4 48.5 18.2 22.  21.3 18.9 12.7 30.3 12.8
 15.3 10.8 30.  26.4 29.9 20.  37.8 33.9 16.9 16.4 43.4 31.6 26.1 23.8
 27.4 56.4 50.4 29.5 23.5 38.5 34.6 48.  66.6 62.5 55.5 64.3 56.  36.7
 32.7 31.2 38.9 38.6 37.1 50.3 46.4 62.4 68.9 62.1 54.2 28.3 28.9 39.2
 29.7 67.  46.2 37.6 45.6 44.7 59.5 61.1 56.8 49.6 53.2 47.7 51.5 52.6
 47.3 50.6 46.1 22.1 51.6 45.4 50.1 45.2 38.  34.5 47.8 43.2 34.1 38.3
 28.2 37.4 33.5 35.4 32.  31.  22.3 29.2 22.2 33.2 36.2 33.7 42.6 41.5
 44.3 39.8 44.8 45.1 40.4 45.8 41.8 47.5 42.7 48.3 43.5 43.8 44.5 49.9
 51.7 51.4 52.  47.1 53.1 53.4 53.5 48.6 48.8 54.5 48.9 54.7 50.  55.8
 50.2 51.  55.6 55.2 54.6 54.  48.4 56.1 52.5 47.6 53.  52.4 47.2 39.
 44.9 41.4 44.6 42.5 43.6 46.7 42.1 43.1 12.  47.4 42.9 32.5 44.  41.9
 35.3 36.  38.4 34.3 38.7 34.  30.8 19.8 17.  15.8 16.7 24.6 25.1 32.2
 44.2 16.3 14.3 17.1 14.9 11.3 19.1 21.4 16.8 42.8 46.  40.3 43.9 23.2
 44.4 67.6 60.5 60.3 69.1 64.1 32.3 65.7 58.3 66.4 57.3 55.1 49.7 44.1
 52.7 40.5 40.1 37.3 33.6 28.7 23.  18.3 28.6 21.9 18.5 36.6 46.9 37.5
 32.4 36.5 62.9 40.  71.4 61.  24.8 25.  46.8 41.7 50.8 23.1 49.1 52.2
 41.2 35.8 56.5 58.8 58.7 16.1 64.  19.2 71.  59.  53.3 43.3 54.3 59.4
 58.9 65.2 53.6 60.4 62.2 56.3 60.6 58.1 45.5 32.8 45.3 33.8 41.6 42.3
 49.3 59.1 57.9 57.7 57.4 37.  53.9 47.9 42.  41.3 42.2 37.9 43.  49.8
 52.3 52.1 36.9 27.9 38.1 40.7 51.9 52.9 35.6 28.4 25.6 49.5 33.1 57.
 31.9 62.   1.  57.8 57.6 58.  58.2 57.5 57.2 55.4 34.4 40.8 40.9 53.7
 59.2 58.6 55.9 60.  36.4 65.3 61.7 63.3 60.8 54.8 61.4 62.8 58.5 60.7
 59.3 61.6 67.9 63.8  0.9 61.5 60.1 59.8 64.5 63.4 61.3 62.7 63.6 63.7
 61.9 61.8 63.9 65.9 71.8 64.2 71.5 67.7 64.4 62.6 72.5 65.4 72.6 74.8
 67.2 63.  62.3 65.5 65.  64.9 65.6 63.5 64.6 67.8 65.8 66.2 68.  67.1
 66.7 64.8 65.1 69.2 69.  66.5 76.7 70.8 66.1 67.3 66.3 71.1 66.9 66.8
 67.4 68.6 68.7]
[20.7 18.  48.6 45.9 14.5 13.  15.5 14.1 13.3 12.1 19.4 17.7 13.2 13.6
 12.3 11.7 10.6 11.1 11.2 10.1 10.9 11.  10.   9.1  8.3  9.6  8.7  9.2
  8.4  7.6  6.8  6.3  5.3  4.8  3.   2.7  2.1  2.3  2.2  3.4  3.2  2.8
  2.5  2.   1.9  1.6  1.5  1.2  0.   1.3  1.7  1.8  2.9  3.1  4.   3.6
  4.5  4.1  5.6  5.2  6.1  8.   7.2  9.7  8.6 10.3  8.5  7.4  8.2  7.8
  8.1  7.3  7.   6.4  6.   6.7  7.7 10.5  9.4 14.7 13.1 20.8 18.5 12.
 17.2 15.3 25.3 22.5 27.5 24.  17.8 15.9 14.4 12.8 20.1 17.9 19.7 14.8
 40.2 35.8 23.8 21.  21.4 19.1 19.9 19.6 17.6 15.6 14.2 15.8 21.3 19.2
 30.5 26.7 28.4 25.7 53.6 48.1 52.4 46.9 26.  23.4 30.3 26.5 23.  20.5
 19.5 17.4 23.5 24.2 21.7 25.1 22.7 18.9 17.  18.4 29.  20.6 46.1 39.3
 60.3 53.9 27.6 57.8 51.4 41.9 35.  24.8 22.2 29.8 25.6 32.6 29.6 69.5
 62.9 27.4 24.5 22.1 28.9 27.2 24.3 19.8 32.2 28.7 23.9 44.5 41.  32.7
 29.3 26.4 24.6 30.2 27.  34.6 31.  39.5 35.3 29.5 26.3 30.7 26.9 23.7
 30.1 20.  19.3 15.1 13.5 13.7 14.3 12.9 11.6  9.9 11.3 10.2 11.4  9.3
 14.9 13.4  5.7  9.   7.9  7.1  5.8  5.   4.6  4.7  4.3  6.6  4.4  3.8
  3.5  2.4  1.4  1.1  3.3  2.6  3.9  4.9  3.7  4.2  5.5  6.9 10.4  8.8
  6.5 16.9 15.  11.5 12.7 11.9 10.7  9.8  6.2 14.  12.5 12.4 15.7 16.4
 17.5  5.4  7.5  5.1  5.9  8.9 16.1 13.9 13.8 17.1 36.9 31.8 29.9 38.9
 34.9 48.4 43.4 50.8 45.6 50.3 46.3 25.9 22.6 54.5 49.1 56.6 53.1 47.8
 31.4 31.5 55.2 56.1 56.2 50.5 56.5 51.  62.5 56.4 27.3 55.  60.6 39.
 39.1 38.7 36.  27.1 25.5 68.7 59.3 20.2 22.9 30.9 16.7 64.  59.1 32.3
 59.7 55.1 37.2 51.3 45.5 35.5 31.3 27.9 36.3 33.  45.2 40.9 59.4 56.
 54.6 38.4 34.  39.8 29.4 21.5 20.3 18.2 20.4 18.1 17.3 31.2 28.1 28.8
 34.4 54.1 49.  37.8 32.4 33.3 53.3 21.6 18.8 15.2 12.6 18.6 10.8  9.5
 16.3 14.6 29.7 37.4 33.7 23.2 18.7 19.  43.  35.9 35.7 22.3 23.6 55.9
 50.1 33.5 29.2 38.  31.6 34.5 47.5 48.5 66.  62.2 40.6 34.3 63.8 55.7
 34.7 30.8 38.5 37.5 16.2 37.  49.8 46.2 61.8 68.3 61.7 64.2 28.2 28.5
 26.2 39.2 25.4 66.4 60.9 24.9 45.7 50.9 50.2 58.9 55.3 54.9 49.4 52.7
 52.8 51.1 51.2 52.2 47.  45.8 24.4 21.8 45.1 49.7 45.  37.7 47.4 42.9
 36.6 33.9 42.  38.1 38.6 38.2 37.3 33.8 36.8 33.4 35.1 34.1 31.1 27.7
 22.  11.8 23.3 35.6 33.1 33.6 37.1 35.4 40.5 36.4 42.1 43.7 44.3 44.4
 40.1 41.6 46.7 42.3 47.7 48.2 43.5 48.9 44.2 49.3 49.9 44.9 50.4 45.4
 50.7 52.1 47.2 52.9 47.6 53.2 48.3 53.8 54.  55.8 50.6 54.3 54.4 49.2
 48.7 53.7 55.5 50.  51.6 51.8 46.8 52.5 51.7 52.6 52.3 47.3 44.6 42.8
 41.1 48.8 48.  46.5 42.2 43.3 42.6 39.4 42.7 44.1 39.6 43.6 37.6 35.2
 34.2 38.3 34.8 30.6 27.8 24.1 25.2 12.2 16.6 31.9 16.8 21.9 25.  32.
 18.3 15.4 20.9 21.2 16.  16.5 42.4 41.5 32.8 39.9 26.8 43.9 22.4 67.
 60.1 31.7 41.7 68.4 63.4 25.8 65.  65.8 59.2 56.7 49.6 41.8 36.5 44.7
 40.3 44.  28.3 36.2 46.4 33.2 24.7 64.9 29.1 70.5 37.9 26.1 23.1 43.2
 58.8 49.5 39.7 41.3 42.5 57.9 58.  22.8 21.1 26.6 63.5 38.8 70.2 58.7
 58.4 64.8 32.9 58.3 59.9 61.6 60.2 57.7 52.  47.1 32.5 28.6 30.  32.1
 40.8 40.  47.9 43.8 46.  51.5 46.6 51.9 56.3 57.5 58.6 53.4 57.1 56.9
 55.6 53.  45.3 43.1 41.2 40.4 40.7 44.8 36.7 30.4 41.4 28.  36.1 53.5
 57.2 57.  57.4 57.3 56.8 62.6 58.5 59.5 59.6 54.2 55.4 54.7 61.  64.6
 59.8 62.3 58.1 60.4 59.  65.7 54.8 60.5 67.4 61.1 68.5 63.2 58.2  0.9
 63.  60.  61.3 57.6 62.7 60.8 61.4 60.7 62.  62.8 63.1 61.2 61.9 62.1
 71.2 63.9 71.  67.1 64.1 71.8 65.1 71.9 74.  66.6 61.5 63.6 63.3 64.7
 64.5 63.7 64.3 67.3 65.2 65.6 66.5 68.8 62.4 66.2 64.4 68.2 65.5 75.8
 70.3 65.4 68.  65.9 67.2 66.9 69.6 66.1 67.9 66.8 66.3]
[20.6 17.7 48.7 45.7 14.5 12.8 15.3 13.9 13.2 11.9 19.3 17.4 14.4 12.9
 13.5 12.  11.5 10.2 12.1 10.8 11.   9.8 10.6 10.9  9.6  8.9  7.9  9.3
  8.2  8.   7.1  6.5  5.7  4.9  4.3  2.7  2.4  1.7  1.6  2.1  1.8  3.1
  2.8  2.2  2.   1.5  1.4  1.3  1.2  1.1  0.   3.2  2.9  3.7  3.3  4.1
  5.2  4.6  6.6  5.8  7.8  6.8  9.4  8.3  9.   8.4  7.4  7.5  6.9  6.
  6.2  5.5  7.3 10.3  9.1 14.7 20.7 18.4 11.6 10.1  9.5 17.1 15.1 25.3
 22.4 27.4 23.9 17.8 15.8 14.3 12.7 20.  19.8 14.8 40.2 35.7 20.9 21.4
 19.  19.6 15.7 14.1 17.5 15.5 19.1 21.5 30.6 26.7 28.5 25.8 53.5 48.

In [7]:
plant_df['Warm'].value_counts()

Warm
0                   32058
0000000000000000    16346
0000000100000000        1
0000001000000001        1
1000000000000001        1
0100000000000000        1
Name: count, dtype: int64

In [25]:
plant_df['fault4'].value_counts()

fault4
0                   32058
0000000000000000    16350
Name: count, dtype: int64

In [16]:
plant_df[plant_df['Warm'] =='0000000100000000']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
4800,334095,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1800,40,5.1,60,60,1,Y,SYSTEM,2025-10-13 14:15:03,\N

In [18]:
plant_df[plant_df['Warm'] =='0000001000000001']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
4802,334097,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1800,40,8.8,60,60,1,Y,SYSTEM,2025-10-13 14:20:03,\N

In [20]:
plant_df[plant_df['Warm'] =='1000000000000001']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
4804,334099,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1800,40,7.1,60,60,1,Y,SYSTEM,2025-10-13 14:25:03,\N

In [19]:
plant_df[plant_df['Warm'] =='0100000000000000']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
4806,334101,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1800,40,9.0,60,60,1,Y,SYSTEM,2025-10-13 14:30:03,\N

In [24]:
plant_df[plant_df['Fault0'] =='0000000000010000']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
4806,334101,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1800,40,9.0,60,60,1,Y,SYSTEM,2025-10-13 14:30:03,\N

In [48]:
plant_df[plant_df['DSPSecuritySpecificationVersionNumr'] =='1GJM_G']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
3353,332648,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,27.1,60,60,1GJM_G,Y,SYSTEM,2025-10-08 12:40:06,\N
7277,336572,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1GJM_G,Y,SYSTEM,2025-10-22 14:40:06,\N
7666,336961,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,3.5,60,60,1GJM_G,Y,SYSTEM,2025-10-24 07:55:14,\N

In [43]:
plant_df['Pfault']

0        0000000000000000
1        0000000000000000
2        0000000000000000
3        0000000000000000
4        0000000000000000
               ...
48437                   0
48438                   0
48439                   0
48440                   0
48441                   0
Name: Pfault, Length: 48408, dtype: object

In [47]:
plant_df[plant_df['Pfault'] == '0000000000000000']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16379,345674,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:20:03,\N
16380,345675,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:25:00,\N
16381,345676,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.4,60,60,1,Y,SYSTEM,2025-11-28 14:25:03,\N
16382,345677,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:30:00,\N
16383,345678,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:30:03,\N

In [34]:
plant_df[plant_df['Device'] != 4034]

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16379,345674,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:20:03,\N
16380,345675,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:25:00,\N
16381,345676,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.4,60,60,1,Y,SYSTEM,2025-11-28 14:25:03,\N
16382,345677,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:30:00,\N
16383,345678,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:30:03,\N

In [26]:
plant_df['BusCapacitance'].value_counts()

BusCapacitance
1880    44464
1784      288
1800      282
1807      275
1786      266
1829      171
1796      146
1799      144
1791      144
1832      144
1803      144
1845      144
1792      144
1817      142
1777      141
1795      140
1808      138
1822      138
1816      134
1810      134
1785      132
1773      132
1839      131
1761      129
1769      127
1870       34
Name: count, dtype: int64

In [27]:
plant_df['AcCapacitance'].value_counts()

AcCapacitance
40    47895
20      513
Name: count, dtype: int64

In [28]:
plant_df['Pdc'].value_counts()

Pdc
0.0     1344
0.8      974
0.9      727
1.0      620
1.1      559
        ...
48.9       1
49.5       1
50.2       1
51.4       1
50.0       1
Name: count, Length: 493, dtype: int64

In [29]:
plant_df['Mode'].value_counts()

Mode
1000    31176
1000    15888
2000      882
2000      462
Name: count, dtype: int64

In [30]:
plant_df.groupby('Mode').size()

Mode
1000    31176
2000      882
1000    15888
2000      462
dtype: int64

In [32]:
plant_df['Mode'].map(repr).value_counts()

Mode
1000      31176
'1000'    15888
2000        882
'2000'      462
Name: count, dtype: int64