In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('total_power.csv')
df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_11200\1163825618.py:1: DtypeWarning: Columns (2,6,7,8,11,36,37,38,39,40,41,42,43,44,46,52,58) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('total_power.csv')

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48437,377732,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.1,60,60,1,Y,SYSTEM,2026-04-08 10:35:03,\N
48438,377733,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,35.5,60,60,1,Y,SYSTEM,2026-04-08 10:40:00,\N
48439,377734,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.7,60,60,1,Y,SYSTEM,2026-04-08 10:40:03,\N
48440,377735,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,36.0,60,60,1,Y,SYSTEM,2026-04-08 10:45:00,\N
48441,377736,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1,Y,SYSTEM,2026-04-08 10:45:03,\N

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48442 entries, 0 to 48441
Data columns (total 63 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQ                                  48442 non-null  int64
 1   PowerPlantID                         48442 non-null  object
 2   Device                               48442 non-null  object
 3   LCDBoot_ARCVersion                   48442 non-null  object
 4   ARCStatus_PVinputConfig              48442 non-null  object
 5   RegNum                               48442 non-null  int64
 6   ProVer                               48442 non-null  object
 7   MinorVer                             48442 non-null  object
 8   SN                                   48442 non-null  object
 9   model                                48442 non-null  object
 10  RWRegSum                             48442 non-null  int64
 11  RWRegAdd                             48442 non-null  object
 12  TYield                               48442 non-null  int64
 13  DYield                               48442 non-null  float64
 14  Eff                                  48442 non-null  int64
 15  PF                                   48442 non-null  float64
 16  Pmax                                 48442 non-null  float64
 17  RunT                                 48442 non-null  float64
 18  Pac                                  48442 non-null  float64
 19  Sac                                  48442 non-null  float64
 20  Uab                                  48442 non-null  float64
 21  Ubc                                  48442 non-null  float64
 22  Uca                                  48442 non-null  float64
 23  la                                   48442 non-null  float64
 24  lb                                   48442 non-null  float64
 25  lc                                   48442 non-null  float64
 26  Upv1                                 48442 non-null  float64
 27  Ipv1                                 48442 non-null  float64
 28  Upv2                                 48442 non-null  float64
 29  Ipv2                                 48442 non-null  float64
 30  Upv3                                 48442 non-null  float64
 31  Ipv3                                 48442 non-null  float64
 32  Freq                                 48442 non-null  float64
 33  Tmod                                 48442 non-null  float64
 34  Tamb                                 48442 non-null  float64
 35  Tcoil                                48442 non-null  float64
 36  Mode                                 48442 non-null  object
 37  Time                                 48442 non-null  object
 38  Pfault                               48442 non-null  object
 39  Warm                                 48442 non-null  object
 40  Fault0                               48442 non-null  object
 41  fault1                               48442 non-null  object
 42  fault2                               48442 non-null  object
 43  fault3                               48442 non-null  object
 44  fault4                               48442 non-null  object
 45  Qac                                  48442 non-null  float64
 46  PIDboxEnable                         48442 non-null  object
 47  PIDboxVoltage                        48442 non-null  float64
 48  PIDboxCurrent                        48442 non-null  float64
 49  Reservedforpidbox                    48442 non-null  object
 50  Reservedforpidbox2                   48442 non-null  object
 51  MajorVer                             48442 non-null  object
 52  PVdetection                          48442 non-null  object
 53  BusCapacitance                       48442 non-null  int64
 54  AcCapacitance                        48442 non-null  int64
 55  Pdc                                  48442 non-null  float64
 56  MaxActivePower                       48442 non-null  int64
 57  MaxApparentPower                     48442 non-null  int64
 58  DSPSecuritySpecificationVersionNumr  48442 non-null  object
 59  use_yn                               48442 non-null  object
 60  crt_usr                              48442 non-null  object
 61  crt_dttm                             48442 non-null  object
 62  udt_dttm                             48442 non-null  object
dtypes: float64(26), int64(9), object(28)
memory usage: 23.3+ MB

In [23]:
plant_df = df[df['PowerPlantID'] == 'GJM_GSG_SGD_0001']
plant_df

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48437,377732,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.1,60,60,1,Y,SYSTEM,2026-04-08 10:35:03,\N
48438,377733,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,35.5,60,60,1,Y,SYSTEM,2026-04-08 10:40:00,\N
48439,377734,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,31.7,60,60,1,Y,SYSTEM,2026-04-08 10:40:03,\N
48440,377735,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282223012,HPC-060HL-V1-0U,...,1880,40,36.0,60,60,1,Y,SYSTEM,2026-04-08 10:45:00,\N
48441,377736,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.0,0.0,1018282225009,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1,Y,SYSTEM,2026-04-08 10:45:03,\N

In [24]:
plant_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48408 entries, 0 to 48441
Data columns (total 63 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SEQ                                  48408 non-null  int64
 1   PowerPlantID                         48408 non-null  object
 2   Device                               48408 non-null  object
 3   LCDBoot_ARCVersion                   48408 non-null  object
 4   ARCStatus_PVinputConfig              48408 non-null  object
 5   RegNum                               48408 non-null  int64
 6   ProVer                               48408 non-null  object
 7   MinorVer                             48408 non-null  object
 8   SN                                   48408 non-null  object
 9   model                                48408 non-null  object
 10  RWRegSum                             48408 non-null  int64
 11  RWRegAdd                             48408 non-null  object
 12  TYield                               48408 non-null  int64
 13  DYield                               48408 non-null  float64
 14  Eff                                  48408 non-null  int64
 15  PF                                   48408 non-null  float64
 16  Pmax                                 48408 non-null  float64
 17  RunT                                 48408 non-null  float64
 18  Pac                                  48408 non-null  float64
 19  Sac                                  48408 non-null  float64
 20  Uab                                  48408 non-null  float64
 21  Ubc                                  48408 non-null  float64
 22  Uca                                  48408 non-null  float64
 23  la                                   48408 non-null  float64
 24  lb                                   48408 non-null  float64
 25  lc                                   48408 non-null  float64
 26  Upv1                                 48408 non-null  float64
 27  Ipv1                                 48408 non-null  float64
 28  Upv2                                 48408 non-null  float64
 29  Ipv2                                 48408 non-null  float64
 30  Upv3                                 48408 non-null  float64
 31  Ipv3                                 48408 non-null  float64
 32  Freq                                 48408 non-null  float64
 33  Tmod                                 48408 non-null  float64
 34  Tamb                                 48408 non-null  float64
 35  Tcoil                                48408 non-null  float64
 36  Mode                                 48408 non-null  object
 37  Time                                 48408 non-null  object
 38  Pfault                               48408 non-null  object
 39  Warm                                 48408 non-null  object
 40  Fault0                               48408 non-null  object
 41  fault1                               48408 non-null  object
 42  fault2                               48408 non-null  object
 43  fault3                               48408 non-null  object
 44  fault4                               48408 non-null  object
 45  Qac                                  48408 non-null  float64
 46  PIDboxEnable                         48408 non-null  object
 47  PIDboxVoltage                        48408 non-null  float64
 48  PIDboxCurrent                        48408 non-null  float64
 49  Reservedforpidbox                    48408 non-null  object
 50  Reservedforpidbox2                   48408 non-null  object
 51  MajorVer                             48408 non-null  object
 52  PVdetection                          48408 non-null  object
 53  BusCapacitance                       48408 non-null  int64
 54  AcCapacitance                        48408 non-null  int64
 55  Pdc                                  48408 non-null  float64
 56  MaxActivePower                       48408 non-null  int64
 57  MaxApparentPower                     48408 non-null  int64
 58  DSPSecuritySpecificationVersionNumr  48408 non-null  object
 59  use_yn                               48408 non-null  object
 60  crt_usr                              48408 non-null  object
 61  crt_dttm                             48408 non-null  object
 62  udt_dttm                             48408 non-null  object
dtypes: float64(26), int64(9), object(28)
memory usage: 23.6+ MB

In [52]:
cols = plant_df.columns[35:]
for col in cols:
    print(plant_df[col].unique())

[0.]
['1000' '2000' 1000 2000]
['2000000000000000' 2000000000000000]
['0000000000000000' 0]
['0000000000000000' '0000000100000000' '0000001000000001'
 '1000000000000001' '0100000000000000' 0]
['0000000000000000' '0000000000010000' 0]
['0000000000000000' '0000000000001000' '1000000000000000' 0]
['0000000000000000' '0000000000000100' '0010000000000000' 0]
['0000000000000000' 0]
['0000000000000000' 0]
[1.0000e+00 9.0000e-01 1.7000e+00 2.5000e+00 8.0000e-01 7.0000e-01
 6.0000e-01 5.0000e-01 4.0000e-01 1.0000e-01 2.0000e-01 3.0000e-01
 0.0000e+00 6.5535e+03 1.1000e+00 1.4000e+00 1.2000e+00 2.2000e+00
 1.8000e+00 2.1000e+00 1.3000e+00 1.9000e+00 2.3000e+00 2.0000e+00
 3.1000e+00 1.6000e+00 1.5000e+00 2.4000e+00 2.6000e+00 2.7000e+00
 4.2000e+00 3.4000e+00 2.8000e+00 6.5534e+03 2.9000e+00 3.0000e+00
 3.3000e+00 6.5533e+03 3.2000e+00 3.6000e+00]
['65535' 65535]
[65535.]
[65535.]
['\\N']
['\\N']
['110f']
['0' 0]
[1870 1829 1880 1800 1845 1803 1832 1799 1792 1791 1807 1786 1795 1822
 1810 1817 1784 1777 1816 1808 1839 1785 1773 1769 1761 1796]
[40 20]
[14.5 12.6 34.1 31.6 10.5  9.3 11.2 10.2  9.6  8.8 13.8 10.4  9.4  9.8
  8.5  7.6  8.9  8.   8.1  7.3  7.9  7.2  6.7  6.   7.   6.3  6.1  5.5
  5.   4.5  3.9  3.5  2.3  2.1  1.7  1.5  1.8  2.6  2.4  1.9  1.6  1.4
  1.1  0.7  0.   0.8  1.   1.2  1.3  3.   2.7  3.3  4.1  3.7  5.1  5.9
  5.3  7.5  6.8  6.2  5.6  5.4  5.7  5.2  4.7  4.8  4.3 14.7 13.1  8.4
  7.4  8.6 12.3 11.  17.9 16.  19.3 16.9 12.8 11.5 10.3 14.3 12.7 14.2
 10.7 28.  24.9 14.9 15.3 13.6 14.  11.3 13.7 21.4 19.1 20.3 18.4 37.6
 33.6 36.7 32.9 16.6 18.7 16.4 12.5 16.8 15.  17.3 15.5 18.  16.2 12.2
 14.8 13.2 20.4 32.  29.1 42.7 38.5 19.8 40.7 36.9 30.2 23.3 17.7 20.9
 23.1 21.1 49.8 45.1 19.5 17.4 15.8 14.1 17.2 20.7 18.6 19.4 22.9 19.
 31.  28.4 23.  20.5 16.7 24.5 21.9 25.  21.3 18.9 10.9  6.6  8.2  8.3
  9.7  8.7  4.2  3.8  5.8  3.4  3.1  4.9  3.2  2.9  2.   0.9  2.5  2.2
  3.6  2.8  4.6  6.5  6.9  9.2  4.4  4.  10.1  9.  10.  11.4 11.7  7.7
 15.2 13.5  9.9 11.1 25.4 20.6 22.8 27.  22.6 26.8 25.9 10.8  9.5 33.8
 30.1 35.6 35.7 31.9 16.1 13.4 38.4 34.2 39.9 37.4 33.4 23.4 14.4 35.8
 11.9 12.  39.8 40.  35.9 20.  17.1 43.1 41.9 19.7 39.6 42.9 38.6 28.2
 29.  27.6 11.8 18.8 49.3 14.6 17.5 46.9 20.2 41.3 28.5 26.7 27.3 25.1
 27.8 25.3 22.  19.6 26.2 21.7 24.8 22.2 31.4 39.3 40.9 37.5 26.3 24.
 24.3 24.1 17.  13.  22.1 19.9 18.2 21.5 37.9 27.2 21.  21.2 25.6 24.4
 12.9 15.4 13.9 12.4 10.6 18.3 13.3  9.1  7.8  7.1  6.4 11.6 20.8 23.5
 16.3 12.1 25.2 25.7 22.7 15.1 21.6 39.4 34.8 24.6 22.4 26.9 36.2 48.7
 43.2 38.7 33.3 43.9 24.7 28.7 16.5 26.6 26.5 32.2 44.1 39.5 43.7 44.9
 36.5 19.2 15.9 17.8 29.7 20.1 47.2 30.9 23.9 34.3 31.5 32.6 42.1 38.9
 43.  38.8 34.4 37.1 37.2 36.1 32.5 36.  32.3 33.1 35.4 17.6 34.7 31.2
 33.  29.8 26.  26.1 23.7 21.8 15.7 23.2 23.8 26.4 23.6 27.4 27.5 28.1
 29.2 30.4 30.7 27.9 30.3 33.5 30.5 31.1 35.1 31.8 32.7 36.6 32.8 37.3
 37.7 33.9 37.8 34.  38.  35.3 39.1 38.2 38.1 33.7 39.2 35.2 36.8 37.
 33.2 34.9 31.7 34.5 32.4 29.6 30.6 27.1 28.9 22.5 29.9 24.2 42.8 18.1
 15.6 47.5 42.2 41.8 48.6 45.4 22.3 46.5 41.  47.1 40.5 36.3 30.8 31.3
 47.  44.6 28.3 50.3 28.6 41.2 35.  29.5 29.3 35.5 18.5 30.  40.4 40.2
 43.6 49.5 39.7 41.7 41.1 25.8 45.5 25.5 29.4 28.8 36.4 40.3 40.1 42.
 39.  42.4 41.4 40.8 34.6 32.1 27.7 38.3 40.6 44.  42.3 42.5 45.  44.3
 42.6 41.6 46.3 48.1 43.3 44.4 48.9 45.2 41.5 44.8 43.4 44.5 43.8 45.7
 50.2 50.  47.4 51.4 46.1 51.  45.6 51.8 45.9 46.  45.8 44.7 44.2 47.6
 47.7 48.5 43.5 45.3 48.2 47.3 46.2 48.4 46.7 54.6 47.9 50.5 48.  49.7
 46.6 46.8 47.8]
[60]
[60]
['1' '1GJM_G' 1]
['Y']
['SYSTEM']
['2025-09-26 15:40:00' '2025-09-26 15:40:03' '2025-09-26 15:45:00' ...
 '2026-04-08 10:40:03' '2026-04-08 10:45:00' '2026-04-08 10:45:03']
['\\N']

In [48]:
plant_df[plant_df['DSPSecuritySpecificationVersionNumr'] =='1GJM_G']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
3353,332648,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,27.1,60,60,1GJM_G,Y,SYSTEM,2025-10-08 12:40:06,\N
7277,336572,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,32.1,60,60,1GJM_G,Y,SYSTEM,2025-10-22 14:40:06,\N
7666,336961,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,3.5,60,60,1GJM_G,Y,SYSTEM,2025-10-24 07:55:14,\N

In [43]:
plant_df['Pfault']

0        0000000000000000
1        0000000000000000
2        0000000000000000
3        0000000000000000
4        0000000000000000
               ...
48437                   0
48438                   0
48439                   0
48440                   0
48441                   0
Name: Pfault, Length: 48408, dtype: object

In [47]:
plant_df[plant_df['Pfault'] == '0000000000000000']

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16379,345674,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:20:03,\N
16380,345675,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:25:00,\N
16381,345676,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.4,60,60,1,Y,SYSTEM,2025-11-28 14:25:03,\N
16382,345677,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:30:00,\N
16383,345678,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:30:03,\N

In [34]:
plant_df[plant_df['Device'] != 4034]

,SEQ,PowerPlantID,Device,LCDBoot_ARCVersion,ARCStatus_PVinputConfig,RegNum,ProVer,MinorVer,SN,model,...,BusCapacitance,AcCapacitance,Pdc,MaxActivePower,MaxApparentPower,DSPSecuritySpecificationVersionNumr,use_yn,crt_usr,crt_dttm,udt_dttm
0,329295,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,14.5,60,60,1,Y,SYSTEM,2025-09-26 15:40:00,\N
1,329296,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,12.6,60,60,1,Y,SYSTEM,2025-09-26 15:40:03,\N
2,329297,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,34.1,60,60,1,Y,SYSTEM,2025-09-26 15:45:00,\N
3,329298,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1829,40,31.6,60,60,1,Y,SYSTEM,2025-09-26 15:45:03,\N
4,329299,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1870,40,10.5,60,60,1,Y,SYSTEM,2025-09-26 15:50:00,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16379,345674,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:20:03,\N
16380,345675,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:25:00,\N
16381,345676,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.4,60,60,1,Y,SYSTEM,2025-11-28 14:25:03,\N
16382,345677,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282223012,HPC-060HL-V1-0U,...,1880,40,30.2,60,60,1,Y,SYSTEM,2025-11-28 14:30:00,\N
16383,345678,GJM_GSG_SGD_0001,4034,ffff,ffff,79,1.00,0.00,1018282225009,HPC-060HL-V1-0U,...,1880,40,27.3,60,60,1,Y,SYSTEM,2025-11-28 14:30:03,\N