In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('total_weather.csv')
df

,weather_info_id,solarpower_sn,base_date,base_time,nx,ny,lgt,pty,rn1,sky,...,reh,rn1v,uuu,vvv,vec,wsd,use_yn,crt_usr_id,crt_dttm,mod_dttm
0,98123,KH_WM_01,20250926,1600,59,75,0,0,강수없음,4,...,54.0,0,0.8,0.1,263,0.8,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:21
1,98124,HDS_SP_E0001,20250926,1600,51,79,0,0,강수없음,4,...,73.0,0,2.8,-0.7,286,2.9,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:21
2,98125,YAG_HSM_SWR_0001,20250926,1600,53,65,0,0,강수없음,4,...,83.0,0,2.0,-0.6,289,2.1,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:21
3,98126,SB_WM_01,20250926,1600,59,74,0,0,강수없음,4,...,50.0,0,1.1,-0.1,280,1.1,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:21
4,98127,GJM_GSG_SGD_0001,20250926,1600,55,74,0,0,강수없음,4,...,59.0,0,1.2,-1.1,315,1.7,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39966,138124,NJS_ACHD_WG_0002,20260408,1000,56,71,0,0,강수없음,1,...,50.0,\N,-0.4,-0.6,34,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N
39967,138125,KH_WM_01,20260408,1000,59,75,0,0,강수없음,1,...,40.0,\N,1.0,0.7,234,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N
39968,138126,SB_WM_01,20260408,1000,59,74,0,0,강수없음,1,...,40.0,\N,0.9,0.5,238,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N
39969,138127,NJS_ROK_GANA_0001,20260408,1000,57,71,0,0,강수없음,1,...,45.0,\N,-0.8,-0.7,48,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N
39970,138128,GJM_GSG_CDAM_0001,20260408,1000,58,76,0,0,강수없음,1,...,50.0,\N,0.4,-1.0,340,1.0,Y,SYSTEM,2026-04-08 09:50:26,\N

In [20]:
moa_df = df[df['solarpower_sn'] == 'GJM_GSG_SGD_0001']
moa_df

,weather_info_id,solarpower_sn,base_date,base_time,nx,ny,lgt,pty,rn1,sky,...,reh,rn1v,uuu,vvv,vec,wsd,use_yn,crt_usr_id,crt_dttm,mod_dttm
4,98127,GJM_GSG_SGD_0001,20250926,1600,55,74,0,0,강수없음,4,...,59.0,0,1.2,-1.1,315,1.7,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:20
10,98133,GJM_GSG_SGD_0001,20250926,1700,55,74,0,0,강수없음,4,...,59.0,0,2.4,-2.0,311,3.2,Y,SYSTEM,2025-09-26 16:50:20,2025-09-26 17:50:21
21,98144,GJM_GSG_SGD_0001,20250926,1800,55,74,0,0,강수없음,4,...,75.0,\N,1.8,-2.0,320,3.0,Y,SYSTEM,2025-09-26 17:50:21,\N
41,98164,GJM_GSG_SGD_0001,20251002,1800,55,74,0,1,1mm 미만,4,...,95.0,\N,0.0,0.9,183,1.0,Y,SYSTEM,2025-10-02 17:50:54,\N
48,98171,GJM_GSG_SGD_0001,20251002,1700,55,74,\N,1,\N,4,...,94.0,0,0.4,0.0,284,0.4,Y,SYSTEM,2025-10-02 17:51:22,2025-10-02 17:51:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39925,138083,GJM_GSG_SGD_0001,20260408,600,55,74,0,0,강수없음,1,...,93.0,0,0.0,0.0,270,0.1,Y,SYSTEM,2026-04-08 05:50:21,2026-04-08 06:50:23
39937,138095,GJM_GSG_SGD_0001,20260408,700,55,74,0,0,강수없음,1,...,79.0,0,0.2,0.0,297,0.2,Y,SYSTEM,2026-04-08 06:50:21,2026-04-08 07:50:26
39949,138107,GJM_GSG_SGD_0001,20260408,800,55,74,0,0,강수없음,1,...,72.0,0,0.6,1.2,207,1.3,Y,SYSTEM,2026-04-08 07:50:23,2026-04-08 08:50:23
39957,138115,GJM_GSG_SGD_0001,20260408,900,55,74,0,0,강수없음,1,...,55.0,0,-1.4,0.9,121,1.7,Y,SYSTEM,2026-04-08 08:50:20,2026-04-08 09:50:22
39962,138120,GJM_GSG_SGD_0001,20260408,1000,55,74,0,0,강수없음,1,...,55.0,\N,0.3,-0.3,321,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N

In [21]:
moa_df.to_csv('./moa_weather.csv', index=False)

In [22]:
moa_df = pd.read_csv('moa_weather.csv')
moa_df

,weather_info_id,solarpower_sn,base_date,base_time,nx,ny,lgt,pty,rn1,sky,...,reh,rn1v,uuu,vvv,vec,wsd,use_yn,crt_usr_id,crt_dttm,mod_dttm
0,98127,GJM_GSG_SGD_0001,20250926,1600,55,74,0,0,강수없음,4,...,59.0,0,1.2,-1.1,315,1.7,Y,SYSTEM,2025-09-26 15:50:20,2025-09-26 16:50:20
1,98133,GJM_GSG_SGD_0001,20250926,1700,55,74,0,0,강수없음,4,...,59.0,0,2.4,-2.0,311,3.2,Y,SYSTEM,2025-09-26 16:50:20,2025-09-26 17:50:21
2,98144,GJM_GSG_SGD_0001,20250926,1800,55,74,0,0,강수없음,4,...,75.0,\N,1.8,-2.0,320,3.0,Y,SYSTEM,2025-09-26 17:50:21,\N
3,98164,GJM_GSG_SGD_0001,20251002,1800,55,74,0,1,1mm 미만,4,...,95.0,\N,0.0,0.9,183,1.0,Y,SYSTEM,2025-10-02 17:50:54,\N
4,98171,GJM_GSG_SGD_0001,20251002,1700,55,74,\N,1,\N,4,...,94.0,0,0.4,0.0,284,0.4,Y,SYSTEM,2025-10-02 17:51:22,2025-10-02 17:51:22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3980,138083,GJM_GSG_SGD_0001,20260408,600,55,74,0,0,강수없음,1,...,93.0,0,0.0,0.0,270,0.1,Y,SYSTEM,2026-04-08 05:50:21,2026-04-08 06:50:23
3981,138095,GJM_GSG_SGD_0001,20260408,700,55,74,0,0,강수없음,1,...,79.0,0,0.2,0.0,297,0.2,Y,SYSTEM,2026-04-08 06:50:21,2026-04-08 07:50:26
3982,138107,GJM_GSG_SGD_0001,20260408,800,55,74,0,0,강수없음,1,...,72.0,0,0.6,1.2,207,1.3,Y,SYSTEM,2026-04-08 07:50:23,2026-04-08 08:50:23
3983,138115,GJM_GSG_SGD_0001,20260408,900,55,74,0,0,강수없음,1,...,55.0,0,-1.4,0.9,121,1.7,Y,SYSTEM,2026-04-08 08:50:20,2026-04-08 09:50:22
3984,138120,GJM_GSG_SGD_0001,20260408,1000,55,74,0,0,강수없음,1,...,55.0,\N,0.3,-0.3,321,1.0,Y,SYSTEM,2026-04-08 09:50:20,\N

In [23]:
cols = moa_df.columns
for col in cols:
    print(moa_df[col].unique())

[ 98127  98133  98144 ... 138107 138115 138120]
['GJM_GSG_SGD_0001']
[20250926 20251002 20251003 20251004 20251005 20251006 20251007 20251008
 20251009 20251010 20251011 20251012 20251013 20251014 20251015 20251016
 20251017 20251018 20251019 20251020 20251021 20251022 20251023 20251024
 20251025 20251027 20251028 20251029 20251030 20251031 20251101 20251103
 20251104 20251105 20251106 20251107 20251108 20251109 20251110 20251111
 20251112 20251113 20251114 20251115 20251117 20251118 20251119 20251120
 20251121 20251122 20251123 20251124 20251125 20251126 20251127 20251128
 20251129 20251130 20251201 20251202 20251203 20251204 20251205 20251206
 20251207 20251208 20251209 20251210 20251211 20251212 20251213 20251214
 20251215 20251216 20251217 20251218 20251219 20251220 20251221 20251222
 20251223 20251224 20251225 20251226 20251227 20251228 20251229 20251230
 20251231 20260101 20260102 20260103 20260104 20260105 20260106 20260107
 20260108 20260109 20260110 20260111 20260112 20260113 20260114 20260115
 20260116 20260117 20260118 20260119 20260120 20260121 20260122 20260123
 20260124 20260125 20260126 20260127 20260128 20260129 20260130 20260131
 20260201 20260202 20260203 20260204 20260205 20260206 20260207 20260208
 20260209 20260210 20260211 20260212 20260213 20260214 20260215 20260216
 20260217 20260218 20260219 20260220 20260221 20260222 20260223 20260224
 20260225 20260226 20260227 20260228 20260301 20260302 20260303 20260304
 20260305 20260306 20260307 20260308 20260309 20260310 20260311 20260312
 20260313 20260314 20260315 20260316 20260317 20260318 20260319 20260320
 20260321 20260322 20260323 20260324 20260325 20260326 20260327 20260328
 20260329 20260330 20260331 20260401 20260402 20260403 20260404 20260405
 20260406 20260407 20260408]
[1600 1700 1800 2000 1900 2100 2200    0 2300  100  200  300  400  600
 1000 1200 1100 1300 1400 1500  500  900  700  800]
[55]
[74]
['0' '\\N']
[   0    1    5 -999    3    2    7]
['강수없음' '1mm 미만' '\\N' '1.0mm' '7.0mm' '9.0mm' '3.0mm' '2.0mm' '4.0mm'
 '5.0mm' '6.0mm' '13.0mm' '11.0mm']
[   4    3    1 -999]
[ 2.62e+01  2.49e+01  2.30e+01  2.00e+01  2.03e+01  1.96e+01  1.97e+01
  1.94e+01  1.90e+01  1.79e+01  1.81e+01  1.72e+01  1.70e+01  1.68e+01
  1.88e+01  1.84e+01  1.85e+01  1.80e+01  1.86e+01  1.87e+01  1.89e+01
  2.09e+01  2.20e+01  2.56e+01  2.45e+01  2.50e+01  2.53e+01  2.60e+01
  2.13e+01  2.15e+01  2.07e+01  2.06e+01  2.10e+01  2.37e+01  2.46e+01
  2.61e+01  2.65e+01  2.52e+01  2.57e+01  2.59e+01  2.43e+01  2.24e+01
  2.17e+01  2.12e+01  2.11e+01  2.04e+01  2.01e+01  2.02e+01  1.92e+01
  1.93e+01  1.95e+01  2.22e+01  2.14e+01  2.42e+01  2.41e+01  2.35e+01
  2.28e+01  2.05e+01  2.29e+01  2.40e+01  2.68e+01  2.36e+01  2.32e+01
  1.98e+01  1.91e+01  2.25e+01  2.72e+01  2.80e+01  2.70e+01  2.54e+01
 -9.99e+02  1.58e+01  1.61e+01  1.60e+01  2.44e+01  2.83e+01  2.51e+01
  2.76e+01  2.21e+01  1.74e+01  1.71e+01  1.64e+01  1.82e+01  2.69e+01
  2.81e+01  2.90e+01  2.82e+01  2.85e+01  2.71e+01  2.19e+01  1.99e+01
  2.26e+01  2.73e+01  2.31e+01  2.23e+01  2.08e+01  2.18e+01  1.78e+01
  1.76e+01  1.69e+01  1.83e+01  1.75e+01  1.56e+01  1.50e+01  1.73e+01
  1.40e+01  1.31e+01  1.43e+01  1.47e+01  1.49e+01  1.20e+01  1.10e+01
  1.57e+01  1.30e+01  1.42e+01  1.21e+01  1.04e+01  1.08e+01  9.00e+00
  1.00e+01  1.41e+01  8.40e+00  6.70e+00  7.40e+00  7.00e+00  6.00e+00
  5.50e+00  4.60e+00  4.70e+00  5.10e+00  4.90e+00  4.00e+00  1.28e+01
  9.70e+00  1.32e+01  1.14e+01  1.24e+01  8.20e+00  3.60e+00  3.10e+00
  2.60e+00  2.20e+00  1.70e+00  1.50e+00  1.30e+00  1.62e+01  4.20e+00
  8.50e+00  1.25e+01  8.60e+00  9.60e+00  7.90e+00  7.10e+00  6.50e+00
  6.20e+00  5.30e+00  5.20e+00  1.02e+01  1.55e+01  1.23e+01  1.13e+01
  1.11e+01  1.15e+01  1.12e+01  1.35e+01  1.48e+01  1.39e+01  1.54e+01
  9.30e+00  8.00e+00  6.30e+00  5.60e+00  5.90e+00  5.70e+00  6.10e+00
  1.07e+01  1.29e+01  1.52e+01  8.70e+00  6.60e+00  5.40e+00  5.00e+00
  4.40e+00  8.90e+00  1.17e+01  1.67e+01  1.06e+01  7.70e+00  7.20e+00
  6.40e+00  4.80e+00  1.33e+01  1.09e+01  9.20e+00  7.30e+00  9.90e+00
  8.10e+00  9.10e+00  1.27e+01  1.44e+01  1.65e+01  1.63e+01  1.36e+01
  8.80e+00  1.16e+01  1.19e+01  1.38e+01  3.00e+00  2.00e+00  1.60e+00
  1.00e+00  7.60e+00  6.80e+00  5.80e+00  3.80e+00  2.80e+00  2.10e+00
  8.30e+00  1.59e+01  1.77e+01  4.50e+00  3.40e+00  2.90e+00  1.80e+00
  1.01e+01  1.53e+01  9.50e+00  7.80e+00  4.30e+00  4.10e+00  3.70e+00
  3.20e+00  3.30e+00  3.50e+00  2.70e+00  3.90e+00  7.50e+00  1.18e+01
  1.34e+01  1.37e+01  1.26e+01  1.22e+01  1.10e+00  3.00e-01  1.00e-01
 -6.00e-01 -1.00e+00  2.00e-01  0.00e+00  6.00e-01  6.90e+00  1.66e+01
  9.40e+00  7.00e-01  8.00e-01  2.50e+00  1.05e+01  2.40e+00 -1.10e+00
 -1.20e+00 -2.00e+00 -1.70e+00 -1.80e+00 -2.40e+00 -2.50e+00 -2.80e+00
  1.51e+01  9.80e+00  1.46e+01  1.03e+01  4.00e-01 -1.00e-01 -1.30e+00
 -5.00e-01 -7.00e-01 -1.50e+00 -1.60e+00 -1.40e+00  2.30e+00  9.00e-01
 -2.60e+00 -4.20e+00 -3.90e+00 -4.90e+00 -5.10e+00 -5.40e+00 -5.90e+00
 -6.30e+00 -6.40e+00 -3.60e+00  1.20e+00  5.00e-01 -2.10e+00 -3.20e+00
 -4.10e+00 -4.30e+00 -4.40e+00 -4.00e-01 -1.90e+00 -3.00e-01 -2.30e+00
 -8.00e-01  1.40e+00  1.90e+00 -2.00e-01 -9.00e-01 -3.10e+00 -3.40e+00
 -3.00e+00 -5.30e+00 -5.00e+00 -6.00e+00 -2.70e+00 -2.20e+00 -6.60e+00
 -5.50e+00 -4.80e+00 -2.90e+00 -6.70e+00 -6.90e+00 -7.10e+00 -7.00e+00
 -7.50e+00 -7.60e+00 -3.50e+00 -3.30e+00 -3.80e+00 -4.00e+00 -6.20e+00
 -7.40e+00 -3.70e+00 -4.50e+00 -4.70e+00 -4.60e+00 -6.50e+00 -5.60e+00
 -5.70e+00 -6.80e+00 -7.30e+00 -7.20e+00 -8.40e+00 -8.10e+00 -8.30e+00
 -5.80e+00 -6.10e+00 -8.50e+00 -8.20e+00 -5.20e+00 -7.70e+00 -7.80e+00
 -8.00e+00  1.45e+01]
[  59.   75.   95.   94.   98.   97.   90.   96.  100.   99.   82.   84.
   80.   83.   70.   86.   73.   68.   72.   79.   89.   91.   92.   85.
   87.   78.   81.   93.   77.   74.   71.   62.   64.   57.   54.   88.
 -998.   40.   48.   46.   63.   55.   52.   49.   53.   47.   69.   76.
   67.   65.   60.   45.   41.   58.   30.   32.   29.   37.   35.   50.
   42.   43.   38.   61.   44.   36.   56.   39.   33.   34.   51.   66.
   27.   23.   25.   26.   28.   31.   24.   22.   14.   16.   19.   21.
   20.   12.   15.   11.   18.]
['0' '\\N' '1' '2' '6' '9' '4' '3' '5' '-999' '7']
[ 1.200e+00  2.400e+00  1.800e+00  0.000e+00  4.000e-01  8.000e-01
  7.000e-01  6.000e-01 -3.000e-01 -9.000e-01 -4.000e-01 -2.000e+00
 -2.700e+00 -5.200e+00 -2.100e+00 -3.000e+00 -2.500e+00 -2.300e+00
 -1.600e+00 -1.800e+00 -1.500e+00 -1.000e-01 -1.400e+00 -5.000e-01
  1.000e-01 -2.000e-01 -6.000e-01  1.000e+00  1.500e+00  1.900e+00
  3.000e+00  2.000e-01  1.300e+00  3.000e-01  1.100e+00  1.600e+00
  2.300e+00  2.700e+00  2.500e+00  1.400e+00  9.000e-01 -2.200e+00
  2.600e+00  3.200e+00  3.400e+00  2.200e+00  2.000e+00  1.700e+00
  2.100e+00 -8.000e-01 -5.290e+01 -1.300e+00 -1.200e+00 -1.000e+00
 -7.000e-01  5.000e-01 -1.700e+00 -1.900e+00 -2.600e+00  3.100e+00
  2.800e+00 -1.100e+00 -9.989e+02 -2.800e+00 -2.400e+00  3.600e+00
  4.300e+00  2.900e+00  4.100e+00  3.300e+00  3.700e+00  3.800e+00
  4.200e+00  3.500e+00  4.900e+00  3.900e+00  4.500e+00  4.600e+00
  5.800e+00  6.300e+00  6.700e+00  7.100e+00  6.200e+00  5.600e+00
  4.700e+00  5.100e+00  4.000e+00  4.800e+00  4.400e+00 -3.500e+00
  5.200e+00  5.000e+00 -3.600e+00 -3.400e+00 -3.300e+00 -3.700e+00
 -3.100e+00 -2.900e+00 -4.400e+00]
[-1.100e+00 -2.000e+00  9.000e-01  0.000e+00  4.000e-01  1.400e+00
  1.200e+00  1.300e+00  8.000e-01 -2.000e-01 -1.000e+00 -5.000e-01
 -1.900e+00 -9.000e-01 -7.000e-01 -1.000e-01 -6.000e-01  2.000e-01
 -4.000e-01  1.000e-01  1.700e+00  1.000e+00  7.000e-01 -3.000e-01
  6.000e-01 -8.000e-01 -1.200e+00  1.500e+00  1.100e+00  2.400e+00
  2.100e+00  1.900e+00  3.000e-01 -1.800e+00 -1.600e+00 -2.100e+00
  2.000e+00  1.600e+00  2.500e+00 -5.290e+01  2.800e+00 -1.500e+00
  5.000e-01 -1.400e+00  3.500e+00  3.600e+00  3.700e+00  1.800e+00
 -2.600e+00 -2.200e+00 -2.300e+00 -2.400e+00 -1.700e+00 -2.700e+00
 -4.500e+00 -9.989e+02 -2.800e+00 -4.100e+00 -4.300e+00 -3.400e+00
 -1.300e+00  2.600e+00 -3.100e+00 -2.500e+00 -3.600e+00 -3.500e+00
 -4.200e+00 -3.300e+00 -3.000e+00 -3.700e+00 -4.000e+00  2.300e+00
 -2.900e+00  4.400e+00  2.900e+00  3.900e+00  4.200e+00  3.300e+00
  2.200e+00 -3.800e+00 -4.400e+00 -5.200e+00 -3.200e+00  3.400e+00
  2.700e+00 -3.900e+00  3.100e+00  4.300e+00  3.000e+00 -4.800e+00
 -4.600e+00 -5.000e+00 -5.300e+00 -6.300e+00 -4.700e+00 -5.100e+00
  5.200e+00  4.700e+00  5.700e+00  5.500e+00  4.800e+00  4.600e+00
  3.200e+00  4.000e+00  4.500e+00  3.800e+00  5.000e+00  5.100e+00]
[ 315  311  320  183  284  243  240  203  159  163  129   59   62   78
   69   66   76   86   74   71   60   96   85  117  330   34  138    0
   56   14  270   63  352   15   97  210  255  242  249  241   82  287
  186  252  276  207  223  309  297  299  272  250  310  293  286  221
  205  288  261  254   90  360   32  108   83  126  130  175  245  233
  231  232  265  279  278  301  274  187  196  171  305  236  317  260
  304  332  307  355  325  290  300    8  322  294  308  312  319  357
  225  214  262   45  333    6   68   67   44  100  161  217  162  131
  141   65  158   27  152  140 -998   70   73   36  114  189  132  164
  156  197  204  227  194  106   40   21  226  201  215  291  328  298
  292  314  302  147  281  321  135  198  166  120  296  283   99  256
  234  313   49  351  335  143  170  192  206  124  101  199  224  277
   24  303   13  251  275  263   16  259   18   41  115  116  119   75
  324  349  247  248    3  149  345  343  306  331   22   28  230  246
  359  266   39   26   52  105  316  354   10    9  216  121  239   38
   35  127  180   72  323   46  228  346  169  253    2  139  211  318
  326  200  280  264  146  208  202   23   31   77  212  218   11  341
  295   53  165  339   84   48  154   89  148   30   29    4  358   33
  347  238  336  342    5   20  167   98  144   37   12   43   19   42
  338  257  337  222  151  285  329  219  235   25   54  282  122  195
  173  112  174   17  344    7  340  348  160  188  172   81  267  229
  209  104   47   58  153  273    1  269   79   88   80  258   64  237
  268  289  190  145  220  350  184  133  107   51  271  113   50   55
  150  191  142  327  356  193  334  111  182  157  178   61  176  168
  109   57   87  353  213  110  185  137   95  155  125   94]
[ 1.700e+00  3.200e+00  3.000e+00  1.000e+00  4.000e-01  9.000e-01
  8.000e-01  1.500e+00  1.400e+00  1.300e+00  6.000e-01  2.400e+00
  6.000e+00  2.600e+00  2.500e+00  1.800e+00  2.200e+00  1.900e+00
  2.000e+00  0.000e+00  1.000e-01  7.000e-01  1.100e+00  1.600e+00
  2.000e-01  3.000e-01  2.300e+00  2.900e+00  3.300e+00  2.100e+00
  4.000e+00  3.100e+00  2.800e+00  2.700e+00 -9.989e+02  1.200e+00
  3.600e+00  4.100e+00  5.000e-01  3.500e+00  3.900e+00  5.000e+00
  5.100e+00  4.300e+00  3.400e+00  3.800e+00  3.700e+00  4.400e+00
  4.200e+00  4.800e+00  4.700e+00  5.500e+00  4.900e+00  4.600e+00
  5.700e+00  5.400e+00  4.500e+00  5.200e+00  5.300e+00  5.900e+00
  5.600e+00  6.600e+00  5.800e+00  6.200e+00  6.100e+00  6.800e+00
  7.200e+00  6.300e+00  6.500e+00  6.700e+00  7.300e+00  7.000e+00
  6.400e+00]
['Y']
['SYSTEM']
['2025-09-26 15:50:20' '2025-09-26 16:50:20' '2025-09-26 17:50:21' ...
 '2026-04-08 07:50:23' '2026-04-08 08:50:20' '2026-04-08 09:50:20']
['2025-09-26 16:50:20' '2025-09-26 17:50:21' '\\N' ...
 '2026-04-08 07:50:26' '2026-04-08 08:50:23' '2026-04-08 09:50:22']